export const MANAGER_ROLES = new Set(['Manager', 'Store Manager']);

export const INCIDENT_TYPES = [
    ['first_aid', 'First Aid'],
    ['medical_aid_no_lost_time', 'Medical Aid – No Lost Time'],
    ['restricted_work', 'Restricted Work'],
    ['lost_time', 'Lost Time'],
    ['fatality', 'Fatality'],
    ['motor_vehicle_incident', 'Motor Vehicle Incident'],
    ['contractor_recordable', 'Contractor Recordable'],
    ['property_damage', 'Property Damage'],
    ['fire_explosion_flood', 'Fire/Explosion/Flood'],
    ['violence_or_harassment', 'Violence or Harassment'],
    ['near_miss', 'Near Miss'],
    ['third_party_incident', '3rd Party Incident (e.g. Public)'],
    ['spill_or_release', 'Spill or Release'],
    ['work_refusal', 'Work Refusal'],
    ['other', 'Other'],
];

export const EVENT_TYPES = [
    ['struck_against', 'Struck against', 1],
    ['struck_by', 'Struck by', 2],
    ['fall_from_elevation', 'Fall from elevation', 3],
    ['fall_on_same_level', 'Fall on same level', 4],
    ['caught_in', 'Caught in', 5],
    ['caught_on', 'Caught on', 6],
    ['caught_between', 'Caught between', 7],
    ['contact_with', 'Contact with', 8],
    ['abnormal_operation', 'Abnormal operation', 9],
    ['product_contamination', 'Product contamination', 10],
    ['overstress_over_exertion_ergonomic', 'Overstress, over exertion, ergonomic', 11],
    ['equipment_failure', 'Equipment failure', 12],
    ['environmental_release', 'Environmental release', 13],
];

export const ACTS = [
    ['act_01', 'Operating equipment without authority', 1],
    ['act_02', 'Failure to warn', 2],
    ['act_03', 'Failure to secure/make safe', 3],
    ['act_04', 'Operating at improper speed', 4],
    ['act_05', 'Making safety devices inoperative', 5],
    ['act_06', 'Using defective equipment', 6],
    ['act_07', 'Failing to use PPE properly', 7],
    ['act_08', 'Improper loading', 8],
    ['act_09', 'Improper placement', 9],
    ['act_10', 'Improper lifting', 10],
    ['act_11', 'Improper position for task', 11],
    ['act_12', 'Servicing equipment in operation', 12],
    ['act_13', 'Horseplay', 13],
    ['act_14', 'Under influence of alcohol and/or drugs', 14],
    ['act_15', 'Using equipment improperly', 15],
    ['act_16', 'Failure to follow procedure/policy/practice', 16],
    ['act_17', 'Failure to identify hazard/risk', 17],
    ['act_18', 'Failure to check/monitor', 18],
    ['act_19', 'Failure to react/correct', 19],
    ['act_20', 'Failure to communicate/coordinate', 20],
];

export const CONDITIONS = [
    ['cond_21', 'Inadequate guards/barriers', 21],
    ['cond_22', 'Inadequate or improper PPE', 22],
    ['cond_23', 'Defective tools, equipment or materials', 23],
    ['cond_24', 'Congestion or restricted action', 24],
    ['cond_25', 'Inadequate warning system', 25],
    ['cond_26', 'Fire and explosion hazards', 26],
    ['cond_27', 'Poor housekeeping/disorder/clutter', 27],
    ['cond_28', 'Noise exposure', 28],
    ['cond_29', 'Radiation exposure', 29],
    ['cond_30', 'Temperature extremes', 30],
    ['cond_31', 'Inadequate or excessive illumination', 31],
    ['cond_32', 'Inadequate ventilation', 32],
    ['cond_33', 'Presence of harmful materials', 33],
    ['cond_34', 'Inadequate instructions/procedures', 34],
    ['cond_35', 'Inadequate information/data', 35],
    ['cond_36', 'Inadequate preparation/planning', 36],
    ['cond_37', 'Inadequate support/assistance', 37],
    ['cond_38', 'Inadequate communications', 38],
    ['cond_39', 'Road conditions', 39],
    ['cond_40', 'Weather conditions', 40],
];

export const ROOT_PERSONAL = [
    ['root_personal_01', 'Inadequate Physical/Physiological Capability', 1],
    ['root_personal_02', 'Inadequate Mental/Psychological Capability', 2],
    ['root_personal_03', 'Physical or Physiological Stress', 3],
    ['root_personal_04', 'Mental or Psychological Stress', 4],
    ['root_personal_05', 'Lack of Knowledge', 5],
    ['root_personal_06', 'Lack of Skill', 6],
    ['root_personal_07', 'Improper Motivation', 7],
    ['root_personal_08', 'Abuse or Misuse', 8],
    ['other', 'Other', null],
];

export const ROOT_JOB = [
    ['root_job_09', 'Inadequate leadership and/or Supervision', 9],
    ['root_job_10', 'Inadequate Engineering', 10],
    ['root_job_11', 'Inadequate Purchasing', 11],
    ['root_job_12', 'Inadequate Maintenance', 12],
    ['root_job_13', 'Inadequate Tools and Equipment', 13],
    ['root_job_14', 'Inadequate Work Standards', 14],
    ['root_job_15', 'Excessive Wear and Tear', 15],
    ['root_job_16', 'Inadequate Communications', 16],
    ['other', 'Other', null],
];

export const CORRECTIVE_AREAS = [
    ['ca_01', 'Leadership and administration', 1],
    ['ca_02', 'Leadership training', 2],
    ['ca_03', 'Planned inspection and maintenance', 3],
    ['ca_04', 'Critical task analysis and procedures', 4],
    ['ca_05', 'Incident investigation', 5],
    ['ca_06', 'Task observation', 6],
    ['ca_07', 'Emergency preparedness', 7],
    ['ca_08', 'Rules and work permits', 8],
    ['ca_09', 'Incident analysis', 9],
    ['ca_10', 'Knowledge and skill training', 10],
    ['ca_11', 'Personal protective equipment', 11],
    ['ca_12', 'Health and hygiene control', 12],
    ['ca_13', 'System evaluation', 13],
    ['ca_14', 'Engineering and change management', 14],
    ['ca_15', 'Personal communications', 15],
    ['ca_16', 'Group communications', 16],
    ['ca_17', 'General promotion', 17],
    ['ca_18', 'Hiring and placement', 18],
    ['ca_19', 'Materials and services management', 19],
    ['ca_20', 'Off-the-job safety', 20],
    ['ca_21', 'Environmental management', 21],
    ['ca_22', 'Quality management', 22],
];

export const SUPPORTING_DOCS = [
    ['doc_hazard_assessment', 'Hazard Assessment', null],
    ['doc_incident_report', 'Incident Report', null],
    ['doc_injury_illness_report', 'Injury/Illness Report', null],
    ['doc_witness_statements', 'Witness Statements', null],
    ['doc_sketch_of_incident_scene', 'Sketch of incident scene', null],
    ['doc_police_report', 'Police Report', null],
    ['doc_photos', 'Photos', null],
    ['other', 'Other', null],
];

export const INVESTIGATION_STEPS = [
    'Basics',
    'Description',
    'Process',
    'Causes',
    'Corrective',
    'Docs & uploads',
    'Sign-off',
    'Review',
];
